# -*- coding: utf-8 -*-
"""EjemploArchivo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zyg1VIaguo4b8pY8KekOqHJuDh_5N_np
"""

def modeloTanque():
  import numpy as np
  import matplotlib.pyplot as plt

  # Problema 0: crear vector de tiempo según indicaciones

  # Problema 1: crear vectores solución

  # Problema 2: condiciones iniciales

  # Problema 3: función para las pendientes

  # Problema 4: parámetros

  # Problema 5: ciclo for

  return tiempo, xA, xB